<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 9</b></center>    
<left><b><h3>Roll No. :101 </b></left>  
<left><b><h3>Name : Aastha Bhojani</b></left>   
<pre>    

### 1. import numpy library.

In [1]:
import numpy as np

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


### 2.Create an array of 10 zeros.

In [8]:
np.zeros(10, dtype = int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 3. Create an array of 10 ones.


In [10]:
np.ones(10, dtype = int)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 4. Create an array of 10 fives.

In [11]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### 5. Create an array of integers from 10 to 50.

In [14]:
arr1=np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 6. Create an array of all the even integers from 10 to 50.

In [16]:
arr1=np.arange(10,50,2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [19]:
arr1=np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 8. Create a 3x3 identity matrix.

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 9. Use Numpy to generate a random number between 0 and 1.

In [21]:
np.random.rand()

0.2795808631352108

### 10. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [22]:
np.random.rand(25)

array([0.88871038, 0.84304006, 0.78495214, 0.94387779, 0.44500863,
       0.78057656, 0.67145586, 0.52885013, 0.74133999, 0.44569989,
       0.30365819, 0.59485707, 0.24385785, 0.07567158, 0.73485233,
       0.47425297, 0.92839379, 0.22006773, 0.89669045, 0.42288489,
       0.58745682, 0.02063542, 0.36431658, 0.5314803 , 0.50930752])

### 11. Create linspace array.

In [24]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### 12. Create an array of 20 linearly spaced points between 0 and 1. 

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### 13. Create Random Integer Array.

In [29]:
np.random.rand(3)

array([0.777713  , 0.17933086, 0.92164871])

### 14. Create Random Integer Array and Reshape that Array.

In [31]:
np.random.rand(9).reshape(3,3)

array([[0.54379193, 0.73671189, 0.28644561],
       [0.37437568, 0.03470124, 0.93145041],
       [0.41456345, 0.93198677, 0.08212561]])