<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 9</b></center>    
<left><b><h3>Roll No. :101 </b></left>  
<left><b><h3>Name :Bhojani Aastha Umeshbhai </b></left>   
<pre>    

### 1. Create a NumPy array of 10 student marks and display its `dtype`, `size`, `ndim`, `shape`, `itemsize`, and `nbytes`.

In [4]:
import numpy as np

In [6]:
marks = np.array([85, 92, 78, 88, 95, 67, 73, 81, 90, 76])

print("Marks:", marks)
print("dtype:", marks.dtype)
print("size:", marks.size)
print("ndim:", marks.ndim)
print("shape:", marks.shape)
print("itemsize:", marks.itemsize)
print("nbytes:", marks.nbytes)


Marks: [85 92 78 88 95 67 73 81 90 76]
dtype: int64
size: 10
ndim: 1
shape: (10,)
itemsize: 8
nbytes: 80


### 2.Create NumPy arrays using zeros, ones, full, arange, linspace, and identity functions.

In [28]:
zeroes=np.zeros((2,3))
ones=np.ones((5,5))
x=np.full((2,3),3)
arrange=np.arange(1,10,3)
l=np.linspace(1,21,4)
i=np.identity(3)


print("Zeroes:",zeroes)
print("Ones:",ones)
print("X:",x)
print("Arange:",arrange)
print("LineSpace:",l)
print("Identity:",i)

Zeroes: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
X: [[3 3 3]
 [3 3 3]]
Arange: [1 4 7]
LineSpace: [ 1.          7.66666667 14.33333333 21.        ]
Identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 3. Create an array of numbers from 1 to 25, reshape it into a 5×5 matrix, and display its transpose.

In [20]:
np.arange(1,26).reshape(5,5).T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

### 4. Generate marks of 20 students randomly between 0 and 100 and find their highest, lowest, and average marks.

In [26]:
marks=np.random.randint(0,101,20)
highest=np.max(marks)
lowest=np.min(marks)
Avg=np.average(marks)
print("Minimun:",highest)
print("Lowest:",lowest)
print("Average:",Avg)

Minimun: 97
Lowest: 8
Average: 46.15


### 5. Generate random numbers using `rand()`, `randn()`, `uniform()`, and `normal()`. Use a seed to reproduce the results.

In [33]:
r=np.random.rand()
rn=np.random.randn()
u=np.random.uniform(1,5,3)
n=np.random.seed(0)
n=np.random.normal(25,5,10)

print("rand",r)
print("randn",rn)
print("Uniform:",u)
print("Normal:",n)

rand 0.09533028175261193
randn -0.45184214239338805
Uniform: [1.37090807 4.1498185  2.85262688]
Normal: [33.82026173 27.00078604 29.89368992 36.204466   34.33778995 20.1136106
 29.75044209 24.24321396 24.48390574 27.05299251]


### 6. Given roll numbers 101–120, randomly select 5 students without replacement and demonstrate shuffling and permutation.

In [34]:
roll_numbers = np.arange(101, 121)
selected = np.random.choice(roll_numbers, 5, replace=False)
np.random.shuffle(roll_numbers)
permuted = np.random.permutation(roll_numbers)
print("5 randomly selected students:")
print(selected)
print("\nAfter shuffling:")
print(roll_numbers)
print("\nRandom permutation:")
print(permuted)


5 randomly selected students:
[112 102 119 118 103]

After shuffling:
[116 114 113 106 112 103 109 107 104 118 105 111 117 119 110 102 101 108
 115 120]

Random permutation:
[115 116 119 113 106 108 107 117 110 101 111 105 118 102 114 120 104 109
 103 112]


### 7. Given marks of 15 students, calculate sum, mean, median, minimum, maximum, variance, and standard deviation.

In [35]:
marks = np.array([78, 85, 92, 67, 74, 88, 95, 81, 69, 90, 76, 84, 73, 89, 80])
print("Marks:",marks)
print("Mean:",np.mean(marks))
print("Mediam:",np.median(marks))
print("Min:",np.min(marks))
print("Max:",np.max(marks))
print("Variance:",np.var(marks))
print("Standard:",np.std(marks))

Marks: [78 85 92 67 74 88 95 81 69 90 76 84 73 89 80]
Mean: 81.4
Mediam: 81.0
Min: 67
Max: 95
Variance: 68.10666666666665
Standard: 8.252676333570017


### 8. Given daily sales for 10 days, calculate total sales, average sales, cumulative sales, and cumulative product.

In [39]:
sales = np.array([120, 150, 100, 180, 200, 160, 140, 220, 190, 170])
total_sales=np.sum(sales)
cum=np.cumprod(sales)
print("Total:",total_sales)
print("cumulative product:",cum)

Total: 1630
cumulative product: [                120               18000             1800000
           324000000         64800000000      10368000000000
    1451520000000000  319334400000000000 5333303778871345152
 2771182796360646656]


### 9. Create two NumPy arrays and perform addition, subtraction, multiplication, division, floor division, modulus, and exponentiation.

In [41]:
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
print("A+B",a+b)
print("A-B",a-b)
print("A*B",a*b)
print("A/B",a/b)
print("A//B",a//b)
print("A**B",a**b)

A+B [11 22 33 44 55]
A-B [ 9 18 27 36 45]
A*B [ 10  40  90 160 250]
A/B [10. 10. 10. 10. 10.]
A//B [10 10 10 10 10]
A**B [       10       400     27000   2560000 312500000]


### 10. Create an unsorted array of student marks and display it in ascending and descending order. Also find the sorted indices.

In [42]:
marks = np.array([78, 85, 92, 67, 74, 88, 95, 81, 69, 90, 76, 84, 73, 89, 80])
aesc=np.sort(marks)
desc=np.sort(marks)[::-1]
sorted_indices=np.argsort(marks)

print("Original:",marks)
print("Aesc:",aesc)
print("Desc:",desc)
print("Sorted indices:", sorted_indices)

Original: [78 85 92 67 74 88 95 81 69 90 76 84 73 89 80]
Aesc: [67 69 73 74 76 78 80 81 84 85 88 89 90 92 95]
Desc: [95 92 90 89 88 85 84 81 80 78 76 74 73 69 67]
Sorted indices: [ 3  8 12  4 10  0 14  7 11  1  5 13  9  2  6]


### 11. Given the following NumPy array:
Write a program to display:

- First 5 elements
- Last 4 elements
- Elements from index 2 to 6
- Every alternate element

In [43]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("1st 5:",arr[:5])
print("Last 4",arr[-4:])
print("index 2 to 6",arr[2:7])
print("Alternet Ele:",arr[::2])

1st 5: [10 20 30 40 50]
Last 4 [ 70  80  90 100]
index 2 to 6 [30 40 50 60 70]
Alternet Ele: [10 30 50 70 90]


### 12. Given the following NumPy array:
Write a program to display:

- The array in reverse order
- Every second element in reverse order
- Last 5 elements in reverse order

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [44]:
print("Reverse:",arr[::-1])
print("Every 2nd Rev:",arr[::-2])
print("Last 5 in rev:",arr[-1:-6:-1])

Reverse: [100  90  80  70  60  50  40  30  20  10]
Every 2nd Rev: [100  80  60  40  20]
Last 5 in rev: [100  90  80  70  60]


### 13. Given following NumPy Array:
Write a program to display:

- First two rows
- Last two rows
- Alternate rows
- Rows from index 1 to 3

In [46]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

In [50]:
print("first 2 rows:",arr[:2])
print("Last 2 rows",arr[-2:])
print("Alternet rows",arr[::2])
print("Rows from index 1 to 3",arr[1:4])

first 2 rows: [[10 20 30 40]
 [50 60 70 80]]
Last 2 rows [[ 90 100 110 120]
 [130 140 150 160]]
Alternet rows [[ 10  20  30  40]
 [ 90 100 110 120]]
Rows from index 1 to 3 [[ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


### 14. Given following NumPy Array:
Write a program to display:
- First two columns
- Last three columns
- First three rows and last two columns
- A 2×3 sub-array from the center

In [52]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

In [56]:
print("First two col:",arr[:,:2])
print("Last three:",arr[:,-3:])
print("First three and last two",arr[:3, -2:])
print("2*3 Sub Array:",arr[1:3,1:4])

First two col: [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
Last three: [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]
First three and last two [[ 4  5]
 [ 9 10]
 [14 15]]
2*3 Sub Array: [[ 7  8  9]
 [12 13 14]]


### 15. Given following NumPy Array:
Write a program to display:
- The matrix with rows in reverse order
- The matrix with columns in reverse order
- The matrix with both rows and columns reversed
- Alternate rows and alternate columns

In [58]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [60]:
print(arr[::-1, :])
print(arr[:,::-1])
print(arr[::-1,::-1])
print(arr[::2,:])
print(arr[::2,::2])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3]
 [ 9 11]]


### 15. Given an array of marks, write a program to display students who scored more than 75 marks.

In [61]:
marks = np.array([45, 78, 62, 89, 35, 91, 56, 73, 40, 84])

In [62]:
print(marks[marks>75])

[78 89 91 84]


### 16. Given an array, write a program to display elements that are greater than 30 and less than 70.

In [63]:
arr = np.array([12, 25, 37, 44, 51, 63, 72, 81, 90, 18])

In [64]:
print(arr[(arr > 30) & (arr < 70)])

[37 44 51 63]


### 17. Given an array, write a program to display elements that are divisible by 5 and greater than 25, and then display elements that are either less than 20 or greater than 45.

In [65]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [66]:
print("Divisible by 5 and greater than 25:")
print(arr[(arr % 5 == 0) & (arr > 25)])

print("Less than 20 or greater than 45:")
print(arr[(arr < 20) | (arr > 45)])


Divisible by 5 and greater than 25:
[30 35 40 45 50 55]
Less than 20 or greater than 45:
[10 15 50 55]
